version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/src/odoo/config
      - ./src:/src
      - ./data_dir:/odoo/data_dir

    links:
      - db
    environment:
      - C_FORCE_ROOT=true
    tty: true
    container_name: backend_odoo

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    container_name: db_odoo
